### ISSUE TITLE
Submitted a PR to use TLS 1.2

### ISSUE THREAD

**Issue by MikeiLL** [devincrossman/mindbody-php-api#11]
From MBO:

"On June 18th, 2018, MINDBODY will no longer accept connections made over TLS 1.0 or TLS 1.1. MINDBODY will only accept TLS 1.2. You may have to change the code in your API integration to accommodate this security change. This update is mandatory, as MINDBODY must be PCI compliant.

The Payment Card Industry (PCI) Data Security Standard has stipulated that TLS 1.0 and 1.1 encryption protocols can no longer be used for secure communications, only TLSv1.2 or higher is acceptable. The PCI DSS standards can be read in full here."

#10

**Comment by devincrossman** [comment]
Thanks for the update @MikeiLL I have merged your PR.
