### ISSUE TITLE
Add more then 1 payment type for split payments.

### ISSUE THREAD

**Issue by donttalktorobots** [devincrossman/mindbody-php-api#3]
Trying to add 2 "PaymentInfo"'s for split payments but only the 2nd one is getting added to the array.  I assume it is because the elements have the same key, but can't seem to find a fancy work around that will work with the API.  Any thoughts?

'Payments' => array(
					        'PaymentInfo' => new SoapVar(
					            array(
					                'LastFour'=>$_POST['stored_cc'], 
					                'Amount'=>$credit_total, 
					            ), 
					            SOAP_ENC_ARRAY, 
					            'StoredCardInfo', 
					            'http://clients.mindbodyonline.com/api/0_5'
					        ),
					        'PaymentInfo' => new SoapVar(
					            array(
					                'Amount'=>$balance_total, 
					            ), 
					            SOAP_ENC_ARRAY, 
					            'DebitAccountInfo', 
					            'http://clients.mindbodyonline.com/api/0_5'
					        )
					    ),

**Comment by devincrossman** [comment]
Should work if you make PaymentInfo an array of SoapVars 

'Payments' => array(
        'PaymentInfo' => array(
		new SoapVar(
        	        array(
				'LastFour'=>'1234',
				'Amount'=>'65',
			),
			SOAP_ENC_ARRAY,
			'StoredCardInfo',
			'http://clients.mindbodyonline.com/api/0_5'
		),
		new SoapVar(
			array(
				'Amount'=>'65',
			),
			SOAP_ENC_ARRAY,
			'DebitAccountInfo',
			'http://clients.mindbodyonline.com/api/0_5'
		)
	)
)
