### ISSUE TITLE
How to get all clients ?

### ISSUE THREAD

**Issue by keshav1990** [devincrossman/mindbody-php-api#7]
When i tried to get clients list it's giving me empty result

**Comment by drfraker** [comment]
If i remember right, you have to pass null for the client ids parameter. I think it's in the docs. What is the message returned by the api?

**Comment by dlm423** [comment]
This worked for me:
`$mb->GetClients(array('XMLDetail'=>'Full','SearchText'=>'','PageSize'=>1000,'CurrentPageIndex'=>0));`

**Comment by keshav1990** [comment]
Thanks , i made that work in other way using CURL and SOAP services

Thanks
Keshav Kalra
Skype Id: keshav.kalra2
Webexe | NeoWebsolutions



[image: --]

Keshav Kalra
[image: https://]about.me/keshavkalra
<https://about.me/keshavkalra?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by annaparthy** [comment]
It was not working for me 
$mb->GetClients(array('XMLDetail'=>'Full','SearchText'=>'','PageSize'=>1000,'CurrentPageIndex'=>0));

**Comment by MikeiLL** [comment]
They are retiring the version 5 API and it's only accessible for old Mindbody accounts. You don't need this SOAP library anymore. Check [the docs](https://developers.mindbodyonline.com/PublicDocumentation/V6).
